name: Deploy PostgreSQL to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - staging

jobs:
  deploy-postgresql:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy PostgreSQL to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "=== Iniciando despliegue de PostgreSQL ==="
          
          # Detener y eliminar contenedor existente si existe
          docker stop postgresql-dev 2>/dev/null || true
          docker rm postgresql-dev 2>/dev/null || true
          docker run -d \
            --name postgresql-dev \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -p 5432:5432 \
            postgres:15