name: Deploy PostgreSQL to EC2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - staging

jobs:
  deploy-postgresql:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH into EC2 and deploy container
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        
    - name: Connect to EC2 and deploy PostgreSQL
      run: |
          # Ejecutar nuevo contenedor PostgreSQL
          docker run -d \
            --name postgresql-dev \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -p 5432:5432 \
            postgres:15
          
          # Esperar a que PostgreSQL esté listo
          echo "Esperando a que PostgreSQL esté listo..."
          sleep 30
          
          # Verificar que el contenedor está corriendo
          docker ps | grep postgresql-dev
          
          # Verificar conectividad a PostgreSQL
          docker exec postgresql-dev pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}
    - name: Verify deployment
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "=== Estado del contenedor PostgreSQL ==="
          docker ps -f name=postgresql-dev
          
          echo "=== Logs del contenedor ==="
          docker logs postgresql-dev --tail 10
          
          echo "=== Verificación de conectividad ==="
          docker exec postgresql-dev psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "SELECT version();"
        EOF 